#	The following module should be in the same folder of this file,
#	It is the module generated using the C library. 
import index

def computeIndex(inputValue):
	#This is the C function:
	return index.index(inputValue)

print('This little script computes the index generated by F-IND')
inputValue = ( 10.0, 10.0)
output = computeIndex(inputValue)
print(output)
